# WallRunner Server Configuration
# 【跨设备联机】绑定到 0.0.0.0 表示监听所有网卡，局域网内其他设备均可访问
# 如果只想本机访问，可改为 127.0.0.1
server.address=0.0.0.0
server.port=8080
spring.application.name=wall-runner-server

# WebSocket
spring.websocket.max-text-message-size=65536
spring.websocket.max-binary-message-size=65536
